services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bricks # dburl="postgresql://postgres:postgres@localhost:5432/bricks?schema=public"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: cache
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  redis-insight:
    container_name: redisinsight-gui
    image: redis/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redis-insight:/data
    depends_on:
      - redis

volumes:
  redis:
    driver: local
  redis-insight:
  postgres-data:
