services:
  redis:
    container_name: cache
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  redis:
    driver: local
 