export type EnvironmentVariables = {
  DATABASE_URL: string;
  ACCESS_TOKEN_EXPIRATION_TIME: string;
  REFRESH_TOKEN_EXPIRATION_TIME: string;
  ACCESS_TOKEN_JWT_KEY: string;
  REFRESH_TOKEN_JWT_KEY: string;
  SENDGRID_API_KEY: string;
  SENDGRID_SENDER: string;
  S3_ACCESS_KEY: string;
  S3_SECRET_ACCESS_KEY: string;
  S3_REGION: string;
  S3_BUCKET_NAME: string;
  JWT_CONFIRMATION_TOKEN_SECRET: string;
  JWT_CONFIRMATION_TOKEN_EXPIRATION_TIME: string;
  CLIENT_DOMAIN: string;
  GOOGLE_OAUTH_CLIENT_ID: string;
  GOOGLE_OAUTH_CLIENT_SECRET: string;
  GOOGLE_OAUTH_CALLBACK_URL: string;
  CLIENT_AUTH_REDIRECT_URL: string;
  GITHUB_OAUTH_CLIENT_ID: string;
  GITHUB_OAUTH_CLIENT_SECRET: string;
  GITHUB_OAUTH_CALLBACK_URL: string;
};

export const ENV: EnvironmentVariables = {
  DATABASE_URL: process.env.DATABASE_URL,
  ACCESS_TOKEN_EXPIRATION_TIME: process.env.ACCESS_TOKEN_EXPIRATION_TIME,
  REFRESH_TOKEN_EXPIRATION_TIME: process.env.REFRESH_TOKEN_EXPIRATION_TIME,
  ACCESS_TOKEN_JWT_KEY: process.env.ACCESS_TOKEN_JWT_KEY,
  REFRESH_TOKEN_JWT_KEY: process.env.REFRESH_TOKEN_JWT_KEY,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_SENDER: process.env.SENDGRID_SENDER,
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
  S3_REGION: process.env.S3_REGION,
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
  JWT_CONFIRMATION_TOKEN_SECRET: process.env.JWT_CONFIRMATION_TOKEN_SECRET,
  JWT_CONFIRMATION_TOKEN_EXPIRATION_TIME:
    process.env.JWT_CONFIRMATION_TOKEN_EXPIRATION_TIME,
  CLIENT_DOMAIN: process.env.CLIENT_DOMAIN,
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_CALLBACK_URL: process.env.GOOGLE_OAUTH_CALLBACK_URL,
  CLIENT_AUTH_REDIRECT_URL: process.env.CLIENT_AUTH_REDIRECT_URL,
  GITHUB_OAUTH_CLIENT_ID: process.env.GITHUB_OAUTH_CLIENT_ID,
  GITHUB_OAUTH_CLIENT_SECRET: process.env.GITHUB_OAUTH_CLIENT_SECRET,
  GITHUB_OAUTH_CALLBACK_URL: process.env.GITHUB_OAUTH_CALLBACK_URL,
};
